/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.*;
import balancecargas.*;
import java.util.ArrayList;
import modelos.*;
/**
 *
 * @author izacc
 */
public class MainThread extends javax.swing.JFrame {

    /**
     * Creates new form MainThread
     */
    public ArrayList<Peticion> listaO;
    public int num;
    
    public MainThread() {
        initComponents(); 
        this.listaO = new ArrayList<>();
        tam1.setEnabled(false);
        tam2.setEnabled(false);
        tam3.setEnabled(false);
        aceptar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tamLista = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tam1 = new javax.swing.JTextField();
        tam2 = new javax.swing.JTextField();
        tam3 = new javax.swing.JTextField();
        aceptar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lista.setEditable(false);
        lista.setColumns(20);
        lista.setRows(5);
        jScrollPane1.setViewportView(lista);

        jLabel1.setText("Id");

        jLabel2.setText("Duracion");

        jButton1.setText("Generar Lista");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tamaño de Lista :");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Tamaño de Nodo 1");

        jLabel5.setText("Tamaño de Nodo 2");

        jLabel6.setText("Tamaño de Nodo 3");

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tam1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(tam2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tam3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptar)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tam3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tamLista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButton1)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tamLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        boolean resultado;
        this.num=0;
        
        try {
            num = Integer.parseInt(this.tamLista.getText());
            if(num < 0)
            {
                num=0;
            }
            if(num>200)
            {
                num=100;
            }
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }
        this.lista.setText("");
        if(resultado==true)
        {
            BalanceCargas bc = new BalanceCargas("lista");
            bc.generarLista(num);
           this.listaO = bc.getLista();
            System.out.println("---------Lista Generada---------\n");
            for (Peticion p: bc.getLista())
            {
                this.lista.setText(""+this.lista.getText()+"\n         "+p.getIdentificador()+"           "+p.getTiempo());
                System.out.println(p.toString());
            }
            
            tam1.setEnabled(true);
            tam2.setEnabled(true);
            tam3.setEnabled(true);
            aceptar.setEnabled(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        boolean resultado;
        
        int num1 = 0;
        int num2 = 0;
        int num3 = 0;
        int total=0;
        int y=0;
        
        try {
                num1 = Integer.parseInt(this.tam1.getText());
                num2 = Integer.parseInt(this.tam2.getText());
                num3 = Integer.parseInt(this.tam3.getText());
                total = num1+num2+num3;
            if(num1<0)
            {
                num1=0;
            }
            if(num2<0)
            {
                num2=0;
            }
            if(num3<0)
            {
                num3=0;
            }
            if(total>this.listaO.size())
            {
                if(num1> num2 && num1 > num3)
                {
                    num1 = this.listaO.size();
                    num2 = 0;
                    num3 = 0;
                }else
                {
                    if(num2 > num1 && num2 > num3)
                    {
                        num1 = 0;
                        num2 = this.listaO.size();
                        num3 = 0;
                    }else
                    {
                        num1 = 0;
                        num2 = 0;
                        num3 = this.listaO.size();
                    }
                }
            }

            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }
        
        
        if(resultado == true)
        {
            ArrayList<Peticion> nodo1 = new ArrayList<>();
            ArrayList<Peticion> nodo2 = new ArrayList<>();
            ArrayList<Peticion> nodo3 = new ArrayList<>();

            if(num1>0)
            {
                for(int x = 0 ; x < num1 ; x++)
                {
                    if(this.listaO.size()>0 && y<num1 )
                    {
                        nodo1.add(this.listaO.get(x));
                        this.listaO.remove(x);
                        x=-1;
                        y++;
                    }
                }
            }
            y=0;
            if(num2>0)
            {
                for(int x = 0 ; x < num2 ; x++)
                {
                    if(this.listaO.size()>0 && y<num2)
                    {
                        nodo2.add(this.listaO.get(x));
                        this.listaO.remove(x);
                        x=-1;
                        y++;
                    }
                }
            }
            y=0;
            if(num3>0)
            {
                for(int x = 0 ; x < num3 ; x++)
                {
                    if(this.listaO.size()>0 && y<num3)
                    {
                        nodo3.add(this.listaO.get(x));
                        this.listaO.remove(x);
                        x=-1;
                        y++;
                    }
                }
            }

            double initialTime = System.currentTimeMillis();

            BalanceCargas bc = new BalanceCargas("Nodo1",num1,nodo1,initialTime,this.listaO);
            BalanceCargas bc1 = new BalanceCargas("Nodo2",num2,nodo2,initialTime,this.listaO);
            BalanceCargas bc2 = new BalanceCargas("Nodo3",num3,nodo3,initialTime,this.listaO);

            bc.start();
            bc1.start();
            bc2.start();
            
            tam1.setEnabled(false);
            tam2.setEnabled(false);
            tam3.setEnabled(false);
            aceptar.setEnabled(false);
        }

    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainThread().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton aceptar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lista;
    private javax.swing.JTextField tam1;
    private javax.swing.JTextField tam2;
    private javax.swing.JTextField tam3;
    private javax.swing.JTextField tamLista;
    // End of variables declaration//GEN-END:variables
}
