/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import modelos.Peticion;

/**
 *
 * @author izacc
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana(String nombre,int tam) 
    {
        initComponents();
        String txt= "EL tamaño es de : "+tam;
        this.nodo.setText(""+nombre+" "+txt+"\n"+"   #    "+"  ID  "+"  Duracion  \n");
        setVisible(true);
    }
    public void mostrarTabla(int num,Peticion p)
    {
        this.nodo.setText(""+this.nodo.getText()+"\n    "+num+"     "+p.getIdentificador()+"        "+p.getTiempo());
    }
    public void terminar(String mensaje)
    {
        this.nodo.setText(""+this.nodo.getText()+"\n\n"+mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nodo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nodo.setEditable(false);
        nodo.setColumns(20);
        nodo.setRows(5);
        jScrollPane1.setViewportView(nodo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea nodo;
    // End of variables declaration//GEN-END:variables
}
